@BASE_URL = http://localhost:5000/sale
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGNlMTFjNDk4MWUwYWMxNTNiNDk5MGQiLCJpYXQiOjE2OTE0Njk4Mjl9.FfGQ0zyLAdalKd54WlcAFupme5d6QRpu8Phn8cKiCww


# Add Sale Request
POST {{BASE_URL}}/add
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###


# Get ALL Sale
GET {{BASE_URL}}/
Content-Type: application/json
Authorization: Bearer {{TOKEN}}
###

# Update User Profile
PATCH {{BASE_URL}}/
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "fullname": "Jenny Doe",
    "bio": "I m great",
    "website": "something.com",
    "address": "Watsicachester",
    "gender": "female"
}

###

# Reset User Code for email and phone
POST {{BASE_URL}}/reset-user-code-for-email-phone
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "email":"smikeybros1000@gmail.com",
    "phone":"+610416659876"
}

###

# Update User Email or Phone
PATCH {{BASE_URL}}/email-phone
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "email":"smikeywork@gmail.com",
    "phone":"+610452369543",
    "resetCode":"950833"
}

###

# Reset User Code
POST {{BASE_URL}}/reset-user-code-for-password
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "email":"smikeywork@gmail.com"
}

###

# Forget Password
PATCH {{BASE_URL}}/new-password
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "email":"smikeywork@gmail.com",
    "resetCode":"334485",
    "newPassword":"smikey"
}

###


# Follow Other User
PATCH {{BASE_URL}}/follow/641527a85472f07085f62875
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###