@BASE_URL = http://localhost:5000/user
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGU2ZDNhMGQ2OTczZWY0YmZiNDZjNjYiLCJpYXQiOjE2OTI5MjYxMzN9.6mNuyI5xqeH2Qf4ynW8YhwjKYj5FA0YFXvv5TodS_3U
# Register Request
POST {{BASE_URL}}/register
Content-Type: application/json

{
    "fullname": "Apple Boy",
    "email":"appleboy472@gmail.com",
    "androidId":"okokok",
    "newPassword":"smikey",
    "countryCode":"+61",
    "phone":"0452369543"
}

###

# Login Request
POST {{BASE_URL}}/login
Content-Type: application/json

{
    "email":"appleboy472@gmail.com",
    "password":"smikey"
}

###

# Get User Detail
GET {{BASE_URL}}/
Content-Type: application/json
Authorization: Bearer {{TOKEN}}
###

# Update User Profile
PATCH {{BASE_URL}}/
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "fullname": "Jenny Doe",
    "bio": "I m great",
    "website": "something.com",
    "address": "Watsicachester",
    "gender": "female"
}

###

# Reset User Code for email and phone
POST {{BASE_URL}}/reset-user-code-for-email-phone
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "email":"smikeybros1000@gmail.com",
    "phone":"+610416659876"
}

###

# Update User Email or Phone
PATCH {{BASE_URL}}/email-phone
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "email":"smikeywork@gmail.com",
    "phone":"+610452369543",
    "resetCode":"950833"
}

###

# Reset User Code
POST {{BASE_URL}}/reset-user-code-for-password
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "email":"smikeywork@gmail.com"
}

###

# Resend Otp
POST {{BASE_URL}}/resend-otp
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###

# Forget Password
PATCH {{BASE_URL}}/new-password
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "email":"smikeywork@gmail.com",
    "resetCode":"170628",
    "newPassword":"smikey"
}

###


# Follow Other User
PATCH {{BASE_URL}}/follow/641527a85472f07085f62875
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###


# Apply Job
POST {{BASE_URL}}/appliedJob/64e7f7ac790e64202452f8db
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###